export const techaMiyaContractAddress =
  "0x5ffc2d8d30c3182b3e8a37d2372dd337b447a6bc";
export const techaMiyaABI = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export const api_url = "https://klaytn-api.fingerlabs.io";

export enum traitTypes {
  Background = "Background",
  Wing = "Wing",
  Hand = "Hand",
  Gloves = "Gloves",
  Weapon = "Weapon",
  Body = "Body",
  Dress = "Dress",
  Face = "Face",
  Eyes = "Eyes",
  Hair = "Hair",
  Mask = "Mask",
  Earring = "Earring",
  Head = "Head",
}

export const background = [
  "Halloween",
  "Auroral Blue",
  "Auroral Green",
  "Auroral Metal Pink",
  "Auroral Metal Purple",
  "Auroral Purple",
  "Auroral Sky Blue",
  "Auroral Forbidden Gold",
];
const wing = [
  "None",
  "Wired Prototype",
  "Jet Pack Purple",
  "Jet Pack Cyan",
  "Fairy Wing Cyan",
  "Fairy Wing Blue",
  "Dragonfly Forbidden Gold",
];
const hand = [
  "Mechanical Hand Titanium",
  "Mechanical Hand Forbidden Gold",
  "Supporting Hand Natural",
  "Supporting Hand Artificial",
  "Grab Hand Natural",
  "Grab Hand Artificial",
  "Halloween",
];
const gloves = [
  "None",
  "Leather Gloves",
  "Silk Gloves Black",
  "Silk Gloves Purple",
  "Silk Gloves Forbidden Gold",
];
const weapon = [
  "None",
  "Plasma Blade Purple",
  "Plasma Blade Red",
  "Drone Grenade",
  "Shuriken Blue S",
  "Shuriken Purple S",
  "Shuriken Blue M",
  "Shuriken Pink M",
  "Shuriken Blue G",
  "Plasma Battle Axe Purple",
  "Plasma Battle Axe Turquoise",
  "AR Screen",
  "Ray Revolver Purple",
  "Ray Revolver Turquoise",
  "Grenade Blue",
  "Plasma Glaive Dark",
  "Plasma Glaive Blue",
  "Plasma Glaive Purple",
  "Moebius Blade Black",
  "Moebius Blade Blue",
  "Moebius Blade Pink",
  "Halloween Wine",
  "Grenade Forbidden Gold",
];
const body = ["Natural Body", "Machine Body", "Halloween"];

const face = [
  "Rascal Face",
  "Rascal Face2",
  "Rascal Face3",
  "Sulky Face",
  "Sulky Face2",
  "Sulky Face3",
  "Wink Face",
  "Wink Face2",
  "Wink Face3",
  "Halloween",
];

const dress = [
  "Optical Camouflage Green",
  "Optical Camouflage Black",
  "Optical Camouflage Blue",
  "Qipao Techa Blue",
  "Qipao Blue",
  "Qipao Techa Pink",
  "Qipao Pink",
  "Open Heart Black",
  "Open Heart Purple",
  "Crop Top Techa Black",
  "Crop Top Pink",
  "Crop Top Techa Pink",
  "Crop Top Techa Blue",
  "Crop Top Blue",
  "Armored Top Green",
  "Leather Vest Techa Blue",
  "Leather Vest Blue",
  "Hanging Neck Blue",
  "Hanging Neck Wine",
  "Layered Tanktop Techa Pink",
  "Layered Tanktop Pink",
  "Layered Tanktop Techa Purple",
  "Layered Tanktop Purple",
  "Pilot Suit Darkblue",
  "Pilot Suit Purple",
  "See-through Hanging Neck Wine",
  "See-through Hanging Neck Purple",
  "Zip Up Top Pink",
  "Zip Up Top Techa Pink",
  "Zip Up Top Orange",
  "Zip Up Top Techa Orange",
  "Overalls Techa Pink",
  "Overalls Pink",
  "Overalls Techa Blue",
  "Overalls Blue",
  "Trench Coat Blue",
  "Halloween",
];

const eyes = [
  "Basic Eye",
  "Basic Eye2",
  "Basic Eye3",
  "Basic Eye4",
  "Basic Eye5",
  "Staring Eye",
  "Staring Eye2",
  "Staring Eye3",
  "Staring Eye4",
  "Staring Eye5",
  "Rascal Eye",
  "Rascal Eye2",
  "Rascal Eye3",
  "Rascal Eye4",
  "Rascal Eye5",
  "Sulky Eye",
  "Sulky Eye2",
  "Sulky Eye3",
  "Sulky Eye4",
  "Sulky Eye5",
  "Wink Eye",
  "Wink Eye2",
  "Wink Eye3",
  "Wink Eye4",
  "Wink Eye5",
  "Halloween",
];

const hair = [
  "Layered highlight Purple",
  "Short Twintail Darkblue",
  "Short Twintail Brown",
  "Long Straight Brown",
  "Long Straight Darkpurple",
  "Long Braid Black",
  "Long Braid Silver",
  "Long Twintail Black",
  "Long Twintail Brown",
  "Short Bang Cyan",
  "Short Bang Blond",
  "Low Twintail Pink",
  "Low Twintail Blond",
  "Curly Short Silver",
  "Curly Short Blond",
  "Short Tomboy Black",
  "Short Tomboy Brown",
  "Short Bob Black",
  "Short Bob Purple",
  "Long Bang Darkblue",
  "Long Bang Black",
  "Fairy Black",
  "Fairy Purple",
  "Fairy Red",
  "Reggae Braids Black",
  "Reggae Braids Blue",
  "Reggae Braids Brown",
  "Reggae Braids Purple",
  "Halloween",
  "Layered highlight Forbidden Gold",
];

const mask = [
  "None",
  "Balaclava Techa Red",
  "Balaclava Red",
  "Optical Niqab Purple",
  "Optical Niqab Black",
  "AR Goggles Purple",
  "AR Goggles Blue",
  "Balaclava Forbidden Gold",
  "Balaclava Techa Forbidden Gold",
];

const earring = [
  "None",
  "Wing Headset Purple",
  "Wing Headset Pink",
  "Ear Cuff Titanium",
  "Arrowhead Earring Red",
  "Arrowhead Earring Purple",
  "Heart Earring Blue",
  "Heart Earring Pink",
  "Heart Earring Silver",
  "Heart Thorn Earrings Silver",
  "Moon Earring Blue",
  "Moon Earring Red",
  "Moon Earring Silver",
  "Plasma Earring Blue",
  "Plasma Earring Silver",
  "Techa Earrings Blue",
  "Techa Earrings Silver",
  "Halloween",
  "Arrowhead Earring Forbidden Gold",
  "BSC Earrings Forbidden Gold",
  "Ear Cuff Forbidden Gold",
  "Heart Thorn Earrings Forbidden Gold",
  "Plasma Earring Forbidden Gold",
];

const head = [
  "None",
  "Hologram Quad Display",
  "Hologram Visor Blue",
  "Hologram Visor Pink",
  "Hologram Headband Blue",
  "Hologram Headband Pink",
  "Metal Horn Pink",
  "Metal Horn Purple",
  "Machine flower Steel",
  "Metal Angelring Purple",
  "Metal Angelring Black",
  "Machine Cat Ears Black",
  "Machine Cat Ears Green",
  "Machine Cat Ears Purple",
  "Halloween",
  "Machine flower Forbidden Gold",
  "Metal Angelring Forbidden Gold",
  "Metal Horn Forbidden Gold",
];

export const options: {
  [key in traitTypes]: string[];
} = {
  [traitTypes.Background]: background,
  [traitTypes.Wing]: wing,
  [traitTypes.Hand]: hand,
  [traitTypes.Gloves]: gloves,
  [traitTypes.Weapon]: weapon,
  [traitTypes.Body]: body,
  [traitTypes.Dress]: dress,
  [traitTypes.Face]: face,
  [traitTypes.Eyes]: eyes,
  [traitTypes.Hair]: hair,
  [traitTypes.Mask]: mask,
  [traitTypes.Earring]: earring,
  [traitTypes.Head]: head,
};
